### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1BQCkD2gKAofIsqmcVp7bB2sauqwVietz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7e9f569090>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

### ISSUE THREAD

**Issue by HXS572** [alefiury/SER-EVO#1]
When I run prepare_datasets.sh, this error occurred in the middle of the run. Do you have any solutions or suggestions?

**Comment by alefiury** [comment]
All links were verified, and when I ran the script, everything was fine. 

You could try updating your version of gdown to the most recent version.
