### ISSUE TITLE
Hello, I can't get the complete dataset using the gdown command, can you share a download link with all the data to me?

### ISSUE THREAD

**Issue by HXS572** [alefiury/SER-EVO#3]

**Comment by alefiury** [comment]
I advise downloading the datasets from the original sources if you are unable to do so using the provided bash script:

[EMOVO](http://voice.fub.it/activities/corpora/emovo/index.html)
[RAVDESS](https://www.kaggle.com/datasets/uwrfkaggler/ravdess-emotional-speech-audio)
[BAVED](https://github.com/40uf411/Basic-Arabic-Vocal-Emotions-Dataset)
[CORAA SER](https://github.com/rmarcacini/ser-coraa-pt-br/)

Running this script (```get_metadata.py```)  will prepare these datasets in a certain format.
